name: ci

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
      matrix:
        preset: [ci-debug, ci-release]
    steps:
      - uses: actions/checkout@v4
      - run: cmake --preset ${{ matrix.preset }}
      - run: cmake --build --preset ${{ matrix.preset }} -j
      - run: ctest --preset ${{ matrix.preset }}
